Update the init script.

diff --git a/templates/default/gitlab_init.erb b/templates/default/gitlab_init.erb
--- a/templates/default/gitlab_init.erb
+++ b/templates/default/gitlab_init.erb
@@ -34,48 +34,62 @@ check_pid(){
 }
 
 start() {
-    cd $APP_ROOT
-    check_pid
-    if [ "$PID" -ne 0 -a "$STATUS" -ne 0 ]; then
-        ## Program is running, exit with error.
-        echo "Error! $DESC $NAME is currently running!"
-        exit 1
-    else
-        if [ `whoami` = root ]; then
-          sudo -u gitlab sh -l -c "nohup bundle exec unicorn_rails $DAEMON_OPTS  > /dev/null  2>&1 &"
-          sudo -u gitlab sh -l -c "mkdir -p $PID_PATH && nohup bundle exec rake environment resque:work QUEUE=post_receive,mailer,system_hook RAILS_ENV=production PIDFILE=$RESQUE_PID  > /dev/null  2>&1 &"
-        fi
-        echo "$DESC started"
+  cd $APP_ROOT
+  check_pid
+  if [ "$PID" -ne 0 -a "$STATUS" -ne 0 ]; then
+    # Program is running, exit with error code 1.
+    echo "Error! $DESC $NAME is currently running!"
+    exit 1
+  else
+    if [ `whoami` = root ]; then
+      sudo -u gitlab -H sh -l -c "nohup bundle exec unicorn_rails $DAEMON_OPTS  > /dev/null  2>&1 &"
+      sudo -u gitlab -H sh -l -c "mkdir -p $PID_PATH && nohup bundle exec rake environment resque:work QUEUE=post_receive,mailer,system_hook RAILS_ENV=production PIDFILE=$RESQUE_PID  > /dev/null  2>&1 &"
+      echo "$DESC started"
     fi
+  fi
 }
 
 stop() {
-    cd $APP_ROOT
-    check_pid
-    if [ "$PID" -ne 0 -a "$STATUS" -ne 0 ]; then
-      ## Program is running, stop it.
-      kill -QUIT `cat $UNICORN_PID`
-      kill -QUIT `cat $RESQUE_PID`
-      rm "$UNICORN_PID" >> /dev/null
-      rm "$RESQUE_PID" >> /dev/null
-      echo "$DESC stopped"
-    else
-      ## Program is not running, exit with error.
-      echo "Error! $DESC not started!"
-      exit 1
-    fi
+  cd $APP_ROOT
+  check_pid
+  if [ "$PID" -ne 0 -a "$STATUS" -ne 0 ]; then
+    ## Program is running, stop it.
+    kill -QUIT `cat $UNICORN_PID`
+    kill -QUIT `cat $RESQUE_PID`
+    rm "$UNICORN_PID" >> /dev/null
+    rm "$RESQUE_PID" >> /dev/null
+    echo "$DESC stopped"
+  else
+    ## Program is not running, exit with error.
+    echo "Error! $DESC not started!"
+    exit 1
+  fi
+}
+
+restart() {
+  cd $APP_ROOT
+  check_pid
+  if [ "$PID" -ne 0 -a "$STATUS" -ne 0 ]; then
+    echo -n "Restarting $DESC: "
+    kill -USR2 `cat $UNICORN_PID`
+    kill -USR2 `cat $RESQUE_PID`
+    echo "$NAME."
+  else
+    echo "Error, $NAME not running!"
+    exit 1
+  fi
 }
 
 status() {
-    cd $APP_ROOT
-    check_pid
-    if [ "$PID" -ne 0 -a "$STATUS" -ne 0 ]; then
-      echo "$DESC with PID $PID is running."
-      exit 0
-    else
-      echo "$DESC is not running."
-      exit 1
-    fi
+  cd $APP_ROOT
+  check_pid
+  if [ "$PID" -ne 0 -a "$STATUS" -ne 0 ]; then
+    echo "$DESC with PID $PID is running."
+    exit 0
+  else
+    echo "$DESC is not running."
+    exit 1
+  fi
 }
 
 ## Check to see if we are running as root first.
@@ -86,25 +100,29 @@ if [ "$(id -u)" != "0" ]; then
 fi
 
 case "$1" in
-    start)
-        start
-        exit 0
-    ;;
-    stop)
-        stop
-        exit 0
-    ;;
-    reload|restart|force-reload)
-        stop
-        sleep 5
-        start
-        exit 0
-    ;;
-    status)
-        status
-    ;;
-    **)
-        echo "Usage: $0 {start|stop|reload}"
-        exit 1
-    ;;
+  start)
+    start
+    exit 0
+  ;;
+  stop)
+    stop
+    exit 0
+  ;;
+  restart)
+    restart
+    exit 0
+  ;;
+  reload|force-reload)
+    echo -n "Reloading $DESC configuration: "
+    kill -HUP `cat $PID`
+    echo "$NAME."
+    exit 0
+  ;;
+  status)
+    status
+  ;;
+  **)
+    echo "Usage: $NAME {start|stop|restart|reload|status}" >&2
+    exit 1
+  ;;
 esac
